// Package uuidify provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package uuidify

// Defines values for GetParamsAlgorithm.
const (
	GetParamsAlgorithmUlid GetParamsAlgorithm = "ulid"
	GetParamsAlgorithmUuid GetParamsAlgorithm = "uuid"
)

// Defines values for GetParamsVersion.
const (
	GetParamsVersionUlid GetParamsVersion = "ulid"
	GetParamsVersionV1   GetParamsVersion = "v1"
	GetParamsVersionV4   GetParamsVersion = "v4"
	GetParamsVersionV7   GetParamsVersion = "v7"
)

// Defines values for GetParamsFormat.
const (
	Json GetParamsFormat = "json"
	Text GetParamsFormat = "text"
)

// GetParams defines parameters for Get.
type GetParams struct {
	// Algorithm Generator algorithm selection
	Algorithm *GetParamsAlgorithm `form:"algorithm,omitempty" json:"algorithm,omitempty"`

	// Version UUID version.
	// When algorithm=ulid, version is ignored and ULIDs are produced.
	Version *GetParamsVersion `form:"version,omitempty" json:"version,omitempty"`

	// Count Number of identifiers to generate.
	Count *int `form:"count,omitempty" json:"count,omitempty"`

	// Format Response format.
	// - `json` → default structured JSON
	// - `text` → newline-delimited plaintext output
	Format *GetParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetParamsAlgorithm defines parameters for Get.
type GetParamsAlgorithm string

// GetParamsVersion defines parameters for Get.
type GetParamsVersion string

// GetParamsFormat defines parameters for Get.
type GetParamsFormat string
